# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-pvc
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
