apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioner-config
data:
  secrets_provisioning.yaml: |
    provisioner:
      policies:
        - name: unlocker
          rules: |
            path "unlocker/data/*" { capabilities = [ "read", "list" ]}
            path "unlocker/metadata/*" { capabilities = [ "read", "list" ]}

        - name: external-secret-operator-policy
          rules: |
            path "cluster/metadata/*" { capabilities = ["read","list"] }
            path "cluster/data/*" { capabilities = ["read","list"] }

      auth:
        - type: userpass
          path: userpass
          users:
            - name: unlocker
              pass: unlocker
              policies:
                - unlocker

        - type: kubernetes
          path: kubernetes

        - type: approle
          path: approle
          approles:
          - name: external-secret-operator
            policies:
              - external-secret-operator-policy
            secret_id_ttl: 3600
            token_ttl: 3600
            token_max_ttl: 7200
            export:
              namespace: security

      mounts:
      - type: kv-v2
        path: unlocker

      - type: kv-v2
        path: cluster
        secrets:
          - path: external/cloudflare/api
            name: token
            data:
              token: "*random*"
          - path: internal/observability/grafana
            name: credentials
            data:
              user: "admin"
              password: "*random*"

      - type: kv-v2
        path: cluster
        secrets:
          - path: internal/kube-bench-exporter/postgres
            name: credential
            data:
              user: "*random*"
              pass: "*random*"

    exporter:
      kubernetes:
        access: in-cluster
