apiVersion: v2
name: vault-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: vault-operator
    version: 0.1.0
    repository: oci://harbor.demo.zebreje.uk/helm
