apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: 1.18.2
appVersion: "1.18.2"
dependencies:
  - name: cert-manager
    version: v1.18.2
    repository: https://charts.jetstack.io
    alias: cert-manager