apiVersion: v2
name: prom-bitnami
description: A Helm chart for Kubernetes
type: application
version: 9.4.3
appVersion: "12.1.1"
dependencies:
  - name: grafana
    version: 9.4.3
    repository: https://grafana.github.io/helm-charts

