apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store-vault-cluster
    kind: ClusterSecretStore
  target:
    name: postgres-kube-bench-credentials
  data:
    - secretKey: api-token
      remoteRef:
        key: external/cloudflare/api/token
        property: token
