apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kube-bench-pg-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store-vault-cluster
    kind: ClusterSecretStore
  target:
    name: kube-bench-pg-credentials
  data:
    - secretKey: user
      remoteRef:
        key: internal/kube-bench-exporter/postgres/credential
        property: user
    - secretKey: pass
      remoteRef:
        key: internal/kube-bench-exporter/postgres/credential
        property: pass
