postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: ""
        username: ""
        password: ""
        database: ""
        existingSecret: ""
        secretKeys:
          adminPasswordKey: ""
          userPasswordKey: ""
          replicationPasswordKey: ""