---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-certificate
spec:
  secretName: harbor-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - "harbor.demo.zebreje.uk"