apiVersion: v2
name: argocd
description: A Helm chart for Kubernetes
type: application
version: 8.3.0
appVersion: "3.1.0"
dependencies:
  - name: argo-cd
    version: 8.3.0
    repository: https://argoproj.github.io/argo-helm
