apiVersion: v2
name: harbor
description: A Helm chart for Kubernetes
type: application
version: 1.18.0
appVersion: "2.14.0"
dependencies:
  - name: harbor
    version: 1.18.0
    repository: https://helm.goharbor.io
