apiVersion: v2
name: arc
description: A Helm chart for Kubernetes
type: application
version: 0.13.0
appVersion: "0.13.0"
dependencies:
  - name: gha-runner-scale-set-controller
    version: 0.13.0
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
