apiVersion: v2
name: arc-set-demo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: gha-runner-scale-set
    version: 0.13.0
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
