apiVersion: v2
name: metallb
description: A Helm chart for Kubernetes
type: application
version: 0.15.2
appVersion: "v0.15.2"
dependencies:
  - name: metallb
    version: 0.15.2
    repository: https://metallb.github.io/metallb
