---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-tls-certificate
spec:
  secretName: ingress-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - "*.demo.zebreje.uk"