{
 "title": "Kube-Bench",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  scan_timestamp AS \"time\",\r\n  cluster_name,\r\n  total_tests,\r\n  passed_tests,\r\n  warning_tests,\r\n  failed_tests\r\nFROM kube_bench_reports\r\nWHERE $__timeFilter(scan_timestamp);\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  scan_timestamp AS \"time\",\r\n  cluster_name,\r\n  passed_tests,\r\n  failed_tests,\r\n  warning_tests\r\nFROM kube_bench_reports\r\nWHERE $__timeFilter(scan_timestamp);\r\n"
    }
   ]
  },
  {
   "title": "Compliance %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  scan_timestamp AS \"time\",\r\n  cluster_name,\r\n  (passed_tests::float / total_tests * 100) AS compliance_percentage\r\nFROM kube_bench_reports\r\nWHERE $__timeFilter(scan_timestamp)\r\nORDER BY scan_timestamp DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Evolution OVer Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  scan_timestamp AS \"time\",\r\n  cluster_name,\r\n  passed_tests AS PASSED,\r\n  failed_tests AS FAILED,\r\n  warning_tests AS WARNING\r\nFROM kube_bench_reports\r\nWHERE $__timeFilter(scan_timestamp)\r\nORDER BY scan_timestamp ASC;\r\n"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Check Listing",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  tr.scan_timestamp AS \"Time\",\r\n  r.cluster_name AS \"Cluster\",\r\n  tr.test_number AS \"Test #\",\r\n  tr.test_description AS \"Description\",\r\n  tr.status AS \"Status\",\r\n  tr.scored AS \"Scored\",\r\n  tr.remediation AS \"Remediation\"\r\nFROM test_results tr\r\nJOIN kube_bench_reports r ON r.id = tr.report_id\r\nJOIN (\r\n    SELECT MAX(scan_timestamp) AS last_scan\r\n    FROM kube_bench_reports\r\n) latest ON r.scan_timestamp = latest.last_scan\r\nORDER BY tr.test_number;\r\n"
    }
   ]
  }
 ]
}